name: Example workflow for Maven using Snyk
on: push
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/020_mid@main
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
